### ISSUE TITLE
Set up issues repository

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/syncfest-campaign#3]
We will need again a issue repository. I can set it up within the mozilla org, if @couci tells me the name I should use.

**Comment by couci** [comment]
This is for where the issues should be opened right? let's use syncfest-volunteersbugs

**Comment by couci** [comment]
@MichaelKohler has this been set up?

**Comment by MichaelKohler** [comment]
Bugs now go to https://github.com/mozilla/syncfest-volunteersbugs/issues
